<img class="img-fluid" src="final_logo.png" alt="Chiaroscuro Coffee" />
<div class="topnav">
<ul>
	<li><a id="navHome" href="final_home.php">Home</a></li>
    <li><a id="navCoffee" href="final_coffee.php">Coffees</a></li>
    <li><a id="navPhoto" href="final_photo.php">Photos</a></li>
    <li><a id="navAdmin" href="final_admin.php">Admin</a></li>
    <li><a id="navLogin" href="final_login.php">Log In</a></li>
</ul>
</div>
