<h2>About our Store</h2>
	 <ul>
		<li><a href="#">Welcome</a></li>
		<li><a href="#">Our Sources</a></li>  
		<li><a href="#">Learn to Roast</a></li>
		<li><a href="#">Custom Blends</a></li>
		<li><a href="#">Roasting Equipment</a></li>
		<li><a href="#">Tasting Notes</a></li>
	 </ul>  
	  <h2>Support</h2>
	  <ul>
		  <li><a href="#">Ordering</a></li>
		  <li><a href="#">Shipping</a></li>
		  <li><a href="#">Returns</a></li>
		  <li><a href="#">FAQs</a></li>
	  </ul>
  
  <blockquote>
  My mornings and after-dinner coffee have never been better since learning to roast at Chiaroscuro Coffee. I save money, too!
  </blockquote>    